export type PcCommandAction =
  | 'LOCK'
  | 'UNLOCK'
  | 'FREEZE'
  | 'UNFREEZE'
  | 'SHUTDOWN'
  | 'RESTART'
  | 'MESSAGE'
  | 'WARNING'
  | 'CAPTURE'
  | 'SIMULATION_START'
  | 'SIMULATION_STOP'
  | 'CHATBOT_ENABLE'
  | 'CHATBOT_DISABLE';

/*
 * ============================================================
 * PC REGISTRATION
 * ============================================================
 */

export interface RegisterPcPayload {
  hostname: string;
  labName?: string;
  sessionId?: string;
  studentId?: string;
}

/*
 * ============================================================
 * PC HEARTBEAT
 * ============================================================
 */

export interface HeartbeatPayload {
  hostname: string;
}

/*
 * ============================================================
 * TEACHER / ADMIN SESSION SUBSCRIPTION
 * ============================================================
 */

export interface TeacherSubscribePayload {
  sessionId: string;
}

/*
 * ============================================================
 * TEACHER / ADMIN COMMAND
 * ============================================================
 */

export interface TeacherCommandPayload {
  sessionId: string;

  /*
   * Specific PC hostname.
   *
   * Use ALL or omit to send the command
   * to every PC connected to the session.
   */

  targetHostname?:
    | string
    | 'ALL';

  action: PcCommandAction;

  /*
   * Required only for MESSAGE.
   */

  message?: string;
}

/*
 * ============================================================
 * COMMAND SENT TO PC
 * ============================================================
 *
 * Generated by the backend.
 *
 * commandId allows us to track:
 *
 * Dashboard
 * -> Server
 * -> PC
 * -> ACK
 * -> Dashboard
 */

export interface PcExecuteCommandPayload {
  commandId: string;

  sessionId: string;

  action: PcCommandAction;

  message?: string;

  issuedBy: string;

  issuedAt: string;
}

/*
 * ============================================================
 * PC COMMAND ACKNOWLEDGEMENT
 * ============================================================
 *
 * PC Agent sends this immediately after executing a command.
 */

export interface PcCommandAckPayload {
  commandId: string;

  hostname: string;

  success: boolean;

  action: PcCommandAction;

  /*
   * ISO timestamp generated by PC Agent.
   */

  executedAt: string;

  /*
   * Optional error information.
   */

  error?: string;

  /*
   * Optional image URL / Base64 data URL for CAPTURE.
   */

  imageUrl?: string;
}

/*
 * ============================================================
 * COMMAND RESULT SENT TO DASHBOARD
 * ============================================================
 *
 * Backend forwards the PC acknowledgement to
 * Admin / Teacher dashboards.
 *
 * latencyMs allows the UI to display:
 *
 * PC-01
 * LOCKED
 * 72 ms
 */

export interface PcCommandResultPayload
  extends PcCommandAckPayload {
  latencyMs?: number;
}

/*
 * ============================================================
 * REGISTER PC VALIDATION
 * ============================================================
 */

export function assertRegisterPcPayload(
  p: any,
): asserts p is RegisterPcPayload {
  if (
    !p ||
    typeof p.hostname !==
      'string' ||
    !p.hostname.trim()
  ) {
    throw new Error(
      'hostname is required',
    );
  }
}

/*
 * ============================================================
 * TEACHER / ADMIN COMMAND VALIDATION
 * ============================================================
 */

export function assertTeacherCommandPayload(
  p: any,
): asserts p is TeacherCommandPayload {
  if (
    !p ||
    typeof p.sessionId !==
      'string' ||
    !p.sessionId.trim()
  ) {
    throw new Error(
      'sessionId is required',
    );
  }

  const validActions:
    PcCommandAction[] = [
      'LOCK',
      'UNLOCK',
      'FREEZE',
      'UNFREEZE',
      'SHUTDOWN',
      'RESTART',
      'MESSAGE',
      'WARNING',
      'CAPTURE',
      'SIMULATION_START',
      'SIMULATION_STOP',
      'CHATBOT_ENABLE',
      'CHATBOT_DISABLE',
    ];

  if (
    !validActions.includes(
      p.action,
    )
  ) {
    throw new Error(
      `action must be one of ${validActions.join(
        ', ',
      )}`,
    );
  }

  if (
    p.action ===
      'MESSAGE' &&
    (
      typeof p.message !==
        'string' ||
      !p.message.trim()
    )
  ) {
    throw new Error(
      'message is required for the MESSAGE action',
    );
  }
}

/*
 * ============================================================
 * PC ACK VALIDATION
 * ============================================================
 */

export function assertPcCommandAckPayload(
  p: any,
): asserts p is PcCommandAckPayload {
  if (
    !p ||
    typeof p.commandId !==
      'string' ||
    !p.commandId.trim()
  ) {
    throw new Error(
      'commandId is required',
    );
  }

  if (
    typeof p.hostname !==
      'string' ||
    !p.hostname.trim()
  ) {
    throw new Error(
      'hostname is required',
    );
  }

  if (
    typeof p.success !==
    'boolean'
  ) {
    throw new Error(
      'success must be a boolean',
    );
  }

  const validActions:
    PcCommandAction[] = [
      'LOCK',
      'UNLOCK',
      'FREEZE',
      'UNFREEZE',
      'SHUTDOWN',
      'MESSAGE',
      'CAPTURE',
    ];

  if (
    !validActions.includes(
      p.action,
    )
  ) {
    throw new Error(
      'Invalid command action',
    );
  }
}
/*
 * ============================================================
 * PC ACTIVITY REPORT
 * ============================================================
 *
 * Sent periodically by the Windows Student Agent.
 *
 * This represents whether the Student was actively
 * interacting with the PC during a sampling period.
 *
 * Examples of activity:
 *
 * - Mouse movement
 * - Mouse click
 * - Keyboard input
 *
 * The Agent calculates activity locally and sends
 * one sample to the backend.
 *
 * IMPORTANT:
 *
 * The backend calculates the final activity percentage.
 * The Student Agent must NOT decide attendance itself.
 */

export interface PcActivityPayload {
  /*
   * PC sending the activity sample.
   */

  hostname: string;

  /*
   * Internal Session UUID.
   */

  sessionId: string;

  /*
   * Whether activity was detected
   * during this sampling interval.
   */

  active: boolean;

  /*
   * Length of the sampling interval.
   *
   * Example:
   * 10 means this sample represents
   * the previous 10 seconds.
   */

  sampleSeconds: number;

  activityPercentage?: number;

  activeApp?: string;

  idleSeconds?: number;

  /*
   * Optional timestamp generated
   * by the Windows Agent.
   */

  recordedAt?: string;
}

/*
 * ============================================================
 * PC ACTIVITY VALIDATION
 * ============================================================
 */

export function assertPcActivityPayload(
  p: any,
): asserts p is PcActivityPayload {
  if (
    !p ||
    typeof p.hostname !==
      'string' ||
    !p.hostname.trim()
  ) {
    throw new Error(
      'hostname is required',
    );
  }

  if (
    typeof p.sessionId !==
      'string' ||
    !p.sessionId.trim()
  ) {
    throw new Error(
      'sessionId is required',
    );
  }

  if (
    typeof p.active !==
    'boolean'
  ) {
    throw new Error(
      'active must be a boolean',
    );
  }

  if (
    typeof p.sampleSeconds !==
      'number' ||
    !Number.isFinite(
      p.sampleSeconds,
    ) ||
    p.sampleSeconds <= 0
  ) {
    throw new Error(
      'sampleSeconds must be a positive number',
    );
  }

  /*
   * Protect the backend from invalid or
   * manipulated very large activity samples.
   *
   * For now, one activity report cannot
   * represent more than 60 seconds.
   */

  if (
    p.sampleSeconds > 60
  ) {
    throw new Error(
      'sampleSeconds cannot exceed 60 seconds',
    );
  }

  /*
   * recordedAt is optional.
   *
   * If provided, it must be a valid
   * ISO-compatible date string.
   */

  if (
    p.recordedAt !==
      undefined
  ) {
    if (
      typeof p.recordedAt !==
        'string' ||
      Number.isNaN(
        Date.parse(
          p.recordedAt,
        ),
      )
    ) {
      throw new Error(
        'recordedAt must be a valid date string',
      );
    }
  }
}